language: node_js
# Use the latest nodejs
node_js:
    - node

sudo: true 

branches:
    only:
        - master

# Cache node_modules for subsequent tests & builds
cache:
    directories:
        - node_modules

# Before Testing & Building app `cd` into 
# the frontend subdirectory, where the react app is located.
before_install:
    - cd frontend

# Test & Build React app before deploying on to Heroku
script:
    - node --version
    - npm -version
    - npm test
    - npm run build

# Deploy 
deploy:
    provider: heroku
    api-key:
        secure: 2ce30bfa-0cd5-4d96-9d6b-08fae54942bd
    app: frontend-bookstore-react-sp

# Slack Notifications
notifications:
  slack:
    template:
      - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch} by %{author} %{result} in %{duration}"
    rooms:
      - aj-vdw7889:d8sCDUQsrGFxKK0dROtUnLqm#general
      - aj-vdw7889:d8sCDUQsrGFxKK0dROtUnLqm#frontend-react-bookstore
    on_success: always # default: always
    on_failure: always # default: always
