# Build rule:
# cd into the frontend/ directory and run the build command.
# Deploy the build/ folder to production.
[build]
    base = "frontend/"
    publish = "build/"
    command = "npm run build" 

# A redirect rule:
# Notifies Netlify to NOT throw an error "page not found" because of React-Router.
# Note: The code below did not work during deployment. So, _redirects page was added to the /public dir.
[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200